vim9script
# hide menu
set guioptions=cM

# make gVim automatically maximize
set lines=999 columns=999

set guifont=Dejavu\ Sans\ Mono\ 12.54
# set guifont=Jetbrains\ Mono\ NL\ Regular\ 12.54

# disable blink cursor
set guicursor+=a:blinkon0

# colorscheme lightsimple
