vim9script
# hide menu
set guioptions=cM

# make gVim automatically maximize
set lines=999 columns=999

set guifont=Jetbrains\ Mono\ NL\ Regular\ 13.5
# set guifont=Jetbrains\ Mono\ NL\ Light\ 13.5

# disable blink cursor
set guicursor+=a:blinkon0

# colorscheme lightsimple
