filetype plugin indent on
syntax on

set ignorecase smartcase incsearch hlsearch
set ruler
set mouse=

set listchars=tab:>\ ,space:.,trail:*,precedes:<,extends:>,eol:$

set encoding=utf-8
set fileencoding=utf-8
set scrolloff=5
set nocompatible

" fix security
set modelines=0
set nomodeline

" save mode: file change detection for watching tools (like docker volumes)
set backupcopy=yes

nnoremap <space> <nop>
xnoremap <space> <nop>
let mapleader="\<Space>"


if has('syntax') && has('eval')
  packadd! matchit
endif

" set backupdir=$HOME/.vim/tmp//,/tmp//
" set nobackup

" for swap files
" swap files is to act as a lock mechanism:
" if you open a file, which is already opened in another Vim session, you’ll be warned
set directory=$HOME/.vim/tmp//,/tmp//

" Persistent undo, even if you close and reopen Vim
" set undodir=$HOME/.vim/tmp//,/tmp//
" set undofile

if has("win32")
  set shellxescape="\"&|<>()@^"
endif
