" Name:         jellybeans_optimized
" Description:  jellybeans import by tools Colortemplate.
" Maintainer:   Original maintainer NanoTech (nanotech.nanotechcorp.net)
" URL:          Original URL https://github.com/nanotech/jellybeans.vim
" License:      Vim License (see `:help license`)

" Generated by Colortemplate v2.2.0

" The color scheme is generated but with some corrections

set background=dark

hi clear
let g:colors_name = 'jellybeans_optimized'

let s:t_Co = exists('&t_Co') && !has('gui_running') ? (&t_Co ?? 0) : -1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conceal Structure
hi! link Conditional Statement
hi! link CurSearch Search
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link EndOfBuffer NonText
hi! link Error ErrorMsg
hi! link Exception Statement
hi! link Float Constant
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link MoreMsg Special
hi! link NERDTreeBookmark Normal
hi! link NERDTreeBookmarkName Identifier
hi! link NERDTreeBookmarksHeader Statement
hi! link NERDTreeBookmarksLeader Ignore
hi! link NERDTreeCWD Statement
hi! link NERDTreeClosable Directory
hi! link NERDTreeCurrentNode Search
hi! link NERDTreeDir Directory
hi! link NERDTreeDirSlash Identifier
hi! link NERDTreeExecFile Title
hi! link NERDTreeFlags Constant
hi! link NERDTreeHelp String
hi! link NERDTreeHelpCommand Identifier
hi! link NERDTreeHelpKey Identifier
hi! link NERDTreeHelpTitle PreProc
hi! link NERDTreeIgnore Ignore
hi! link NERDTreeLinkDir PreProc
hi! link NERDTreeLinkFile PreProc
hi! link NERDTreeLinkTarget Type
hi! link NERDTreeOpenable Directory
hi! link NERDTreePart Special
hi! link NERDTreePartFile Type
hi! link NERDTreeRO WarningMsg
hi! link NERDTreeToggleOff WarningMsg
hi! link NERDTreeToggleOn Question
hi! link NERDTreeUp Directory
hi! link Number Constant
hi! link Operator Structure
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Quote Special
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link Tag Special
hi! link TagListFileName Directory
hi! link Typedef Type
hi! link cFormat Identifier
hi! link cOperator Constant
hi! link cocoaClass Type
hi! link cocoaFunction Function
hi! link coffeeRegExp rubyRegexp
hi! link colortemplateArrow Delimiter
hi! link colortemplateAttr Statement
hi! link colortemplateAttrs String
hi! link colortemplateCommand PreProc
hi! link colortemplateComment Comment
hi! link colortemplateConstant Type
hi! link colortemplateFunction Function
hi! link colortemplateGuisp String
hi! link colortemplateHexColor Constant
hi! link colortemplateHiGroup Identifier
hi! link colortemplateKey Special
hi! link colortemplateKeyword Statement
hi! link colortemplateNumber Constant
hi! link colortemplateSpecial Constant
hi! link colortemplateTermCode String
hi! link colortemplateTodo Todo
hi! link colortemplateVerb Title
hi! link cssAnimationAttr Constant
hi! link cssAnimationProp StorageClass
hi! link cssAtKeyword PreProc
hi! link cssAtRule PreProc
hi! link cssAtRuleLogical Statement
hi! link cssAttr Constant
hi! link cssAttrComma Special
hi! link cssAttributeSelector String
hi! link cssAuralAttr Constant
hi! link cssAuralProp StorageClass
hi! link cssBackgroundAttr Constant
hi! link cssBackgroundProp StorageClass
hi! link cssBorderAttr Constant
hi! link cssBorderProp StorageClass
hi! link cssBoxAttr Constant
hi! link cssBoxProp StorageClass
hi! link cssBraceError ErrorMsg
hi! link cssBraces Function
hi! link cssCascadeAttr Constant
hi! link cssCascadeProp StorageClass
hi! link cssClassName Function
hi! link cssClassNameDot Function
hi! link cssColor Constant
hi! link cssColorProp StorageClass
hi! link cssComment Comment
hi! link cssCommonAttr Constant
hi! link cssContentForPagedMediaAttr Constant
hi! link cssContentForPagedMediaProp StorageClass
hi! link cssCustomProp Special
hi! link cssDeprecated ErrorMsg
hi! link cssDimensionAttr Constant
hi! link cssDimensionProp StorageClass
hi! link cssError ErrorMsg
hi! link cssFlexibleBoxAttr Constant
hi! link cssFlexibleBoxProp StorageClass
hi! link cssFontAttr Constant
hi! link cssFontDescriptor Special
hi! link cssFontDescriptorAttr Constant
hi! link cssFontDescriptorProp StorageClass
hi! link cssFontProp StorageClass
hi! link cssFunction Constant
hi! link cssFunctionComma Function
hi! link cssFunctionName Function
hi! link cssGeneratedContentAttr Constant
hi! link cssGeneratedContentProp StorageClass
hi! link cssGradientAttr Constant
hi! link cssGridAttr Constant
hi! link cssGridProp StorageClass
hi! link cssHacks Comment
hi! link cssHyerlinkAttr Constant
hi! link cssHyerlinkProp StorageClass
hi! link cssIEUIAttr Constant
hi! link cssIEUIProp StorageClass
hi! link cssIdentifier Function
hi! link cssImportant Special
hi! link cssInteractAttr Constant
hi! link cssInteractProp StorageClass
hi! link cssKeyFrameProp Constant
hi! link cssLineboxAttr Constant
hi! link cssLineboxProp StorageClass
hi! link cssListAttr Constant
hi! link cssListProp StorageClass
hi! link cssMarginAttr Constant
hi! link cssMarqueeAttr Constant
hi! link cssMarqueeProp StorageClass
hi! link cssMediaAttr Constant
hi! link cssMediaComma Normal
hi! link cssMediaProp StorageClass
hi! link cssMediaType Special
hi! link cssMobileTextProp StorageClass
hi! link cssMultiColumnAttr Constant
hi! link cssMultiColumnProp StorageClass
hi! link cssNoise Noise
hi! link cssObjectAttr Constant
hi! link cssObjectProp StorageClass
hi! link cssPaddingAttr Constant
hi! link cssPageMarginProp PreProc
hi! link cssPageProp StorageClass
hi! link cssPagePseudo PreProc
hi! link cssPagedMediaAttr Constant
hi! link cssPagedMediaProp StorageClass
hi! link cssPositioningAttr Constant
hi! link cssPositioningProp StorageClass
hi! link cssPrintAttr Constant
hi! link cssPrintProp StorageClass
hi! link cssProp StorageClass
hi! link cssPseudoClassId PreProc
hi! link cssPseudoClassLang Constant
hi! link cssRenderAttr Constant
hi! link cssRenderProp StorageClass
hi! link cssRubyAttr Constant
hi! link cssRubyProp StorageClass
hi! link cssSelectorOp Special
hi! link cssSelectorOp2 Special
hi! link cssSpeechAttr Constant
hi! link cssSpeechProp StorageClass
hi! link cssStringQ String
hi! link cssStringQQ String
hi! link cssTableAttr Constant
hi! link cssTableProp StorageClass
hi! link cssTagName Statement
hi! link cssTextAttr Constant
hi! link cssTextProp StorageClass
hi! link cssTransformAttr Constant
hi! link cssTransformProp StorageClass
hi! link cssTransitionAttr Constant
hi! link cssTransitionProp StorageClass
hi! link cssUIAttr Constant
hi! link cssUIProp StorageClass
hi! link cssURL String
hi! link cssUnicodeEscape Special
hi! link cssUnicodeRange Constant
hi! link cssUnitDecorators Constant
hi! link cssValueAngle Constant
hi! link cssValueFrequency Constant
hi! link cssValueInteger Constant
hi! link cssValueLength Constant
hi! link cssValueNumber Constant
hi! link cssValueTime Constant
hi! link cssVendor Comment
hi! link diffAdded String
hi! link diffRemoved Constant
hi! link dtdAttrDef Type
hi! link dtdAttrType Type
hi! link dtdCard Function
hi! link dtdComment Comment
hi! link dtdConstant Constant
hi! link dtdEntity Statement
hi! link dtdEntityPunct Type
hi! link dtdEnum Constant
hi! link dtdError ErrorMsg
hi! link dtdFunction Function
hi! link dtdParamEntityDPunct Comment
hi! link dtdParamEntityDecl Type
hi! link dtdParamEntityInst Constant
hi! link dtdParamEntityPunct Type
hi! link dtdString Constant
hi! link dtdTag Normal
hi! link dtdTagName Statement
hi! link dtdTodo Todo
hi! link dtdType Type
hi! link elixirAtom rubySymbol
hi! link erlangAtom rubySymbol
hi! link erlangBIF rubyPredefinedIdentifier
hi! link erlangDirective Statement
hi! link erlangFunction rubyPredefinedIdentifier
hi! link erlangNode Identifier
hi! link helpBacktick Ignore
hi! link helpBar Ignore
hi! link helpBoolean Constant
hi! link helpCharacter Constant
hi! link helpCommand Comment
hi! link helpComment Comment
hi! link helpConditional Statement
hi! link helpConstant Constant
hi! link helpDebug Special
hi! link helpDefine PreProc
hi! link helpDelimiter Delimiter
hi! link helpDeprecated Todo
hi! link helpError ErrorMsg
hi! link helpExample Comment
hi! link helpException Statement
hi! link helpFloat Constant
hi! link helpFunction Function
hi! link helpHeader PreProc
hi! link helpHeadline Statement
hi! link helpHyperTextEntry String
hi! link helpHyperTextJump Identifier
hi! link helpIdentifier Identifier
hi! link helpIgnore Ignore
hi! link helpInclude PreProc
hi! link helpKeyword Statement
hi! link helpLabel Statement
hi! link helpMacro PreProc
hi! link helpNotVi Special
hi! link helpNote Todo
hi! link helpNumber Constant
hi! link helpOperator Structure
hi! link helpOption Type
hi! link helpPreCondit PreProc
hi! link helpPreProc PreProc
hi! link helpRepeat Statement
hi! link helpSectionDelim PreProc
hi! link helpSpecial Special
hi! link helpSpecialChar Special
hi! link helpSpecialComment Special
hi! link helpStar Ignore
hi! link helpStatement Statement
hi! link helpStorageClass StorageClass
hi! link helpString String
hi! link helpStructure Structure
hi! link helpTag Special
hi! link helpTodo Todo
hi! link helpType Type
hi! link helpTypedef Type
hi! link helpURL String
hi! link helpUnderlined Underlined
hi! link helpVim Identifier
hi! link helpWarning Todo
hi! link htmlArg Type
hi! link htmlBoldItalicUnderline htmlBoldUnderlineItalic
hi! link htmlComment Comment
hi! link htmlCommentError ErrorMsg
hi! link htmlCommentNested ErrorMsg
hi! link htmlCssDefinition Special
hi! link htmlCssStyleComment Comment
hi! link htmlEndTag Statement
hi! link htmlError ErrorMsg
hi! link htmlEvent Special
hi! link htmlEventDQ Special
hi! link htmlEventSQ Special
hi! link htmlH1 Title
hi! link htmlH2 Title
hi! link htmlH3 Title
hi! link htmlH4 Title
hi! link htmlH5 Title
hi! link htmlH6 Title
hi! link htmlHead PreProc
hi! link htmlItalicBold htmlBoldItalic
hi! link htmlItalicBoldUnderline htmlBoldUnderlineItalic
hi! link htmlItalicUnderline htmlUnderlineItalic
hi! link htmlItalicUnderlineBold htmlBoldUnderlineItalic
hi! link htmlLeadingSpace None
hi! link htmlLink Underlined
hi! link htmlMathTagName Statement
hi! link htmlPreAttr String
hi! link htmlPreError ErrorMsg
hi! link htmlPreProc PreProc
hi! link htmlPreProcAttrError ErrorMsg
hi! link htmlPreProcAttrName PreProc
hi! link htmlPreStmt PreProc
hi! link htmlScriptTag Statement
hi! link htmlSpecialChar Special
hi! link htmlSpecialTagName Statement
hi! link htmlStatement Statement
hi! link htmlString String
hi! link htmlStyleArg String
hi! link htmlSvgTagName Statement
hi! link htmlTag Statement
hi! link htmlTagError ErrorMsg
hi! link htmlTagName Statement
hi! link htmlTitle Title
hi! link htmlUnderlineBold htmlBoldUnderline
hi! link htmlUnderlineBoldItalic htmlBoldUnderlineItalic
hi! link htmlUnderlineItalicBold htmlBoldUnderlineItalic
hi! link htmlValue String
hi! link javaScrParenError ErrorMsg
hi! link javaScript Special
hi! link javaScriptBoolean Constant
hi! link javaScriptBraces Function
hi! link javaScriptBranch Statement
hi! link javaScriptCharacter Constant
hi! link javaScriptComment Comment
hi! link javaScriptCommentTodo Todo
hi! link javaScriptConditional Statement
hi! link javaScriptConstant Statement
hi! link javaScriptDebug Special
hi! link javaScriptDeprecated Statement
hi! link javaScriptEmbed Special
hi! link javaScriptError ErrorMsg
hi! link javaScriptException Statement
hi! link javaScriptExpression Special
hi! link javaScriptFunction Function
hi! link javaScriptGlobal Statement
hi! link javaScriptIdentifier Identifier
hi! link javaScriptLabel Statement
hi! link javaScriptLineComment Comment
hi! link javaScriptMember Statement
hi! link javaScriptMessage Statement
hi! link javaScriptNull Statement
hi! link javaScriptNumber Constant
hi! link javaScriptOperator Structure
hi! link javaScriptRegexpString rubyRegexp
hi! link javaScriptRepeat Statement
hi! link javaScriptReserved Statement
hi! link javaScriptSpecial Special
hi! link javaScriptSpecialCharacter Special
hi! link javaScriptStatement Statement
hi! link javaScriptStringD String
hi! link javaScriptStringS String
hi! link javaScriptStringT String
hi! link javaScriptTemplateDelim Identifier
hi! link javaScriptTemplateString String
hi! link javaScriptTemplateVar StringDelim
hi! link javaScriptType Type
hi! link javaScriptValue Constant
hi! link kshSpecialVariables PreProc
hi! link kshStatement Statement
hi! link luaOperator Statement
hi! link markdownAutomaticLink Constant
hi! link markdownBlockquote Comment
hi! link markdownBold htmlBold
hi! link markdownBoldDelimiter htmlBold
hi! link markdownBoldItalic htmlBoldItalic
hi! link markdownBoldItalicDelimiter htmlBoldItalic
hi! link markdownCodeDelimiter Delimiter
hi! link markdownError ErrorMsg
hi! link markdownEscape Special
hi! link markdownFootnote Type
hi! link markdownFootnoteDefinition Type
hi! link markdownH1 Title
hi! link markdownH1Delimiter Delimiter
hi! link markdownH2 Title
hi! link markdownH2Delimiter Delimiter
hi! link markdownH3 Title
hi! link markdownH3Delimiter Delimiter
hi! link markdownH4 Title
hi! link markdownH4Delimiter Delimiter
hi! link markdownH5 Title
hi! link markdownH5Delimiter Delimiter
hi! link markdownH6 Title
hi! link markdownH6Delimiter Delimiter
hi! link markdownHeadingDelimiter Delimiter
hi! link markdownHeadingRule PreProc
hi! link markdownId Type
hi! link markdownIdDeclaration Type
hi! link markdownIdDelimiter markdownLinkDelimiter
hi! link markdownItalic htmlItalic
hi! link markdownItalicDelimiter htmlItalic
hi! link markdownLinkText Underlined
hi! link markdownListMarker Statement
hi! link markdownOrderedListMarker Statement
hi! link markdownRule PreProc
hi! link markdownUrl Constant
hi! link markdownUrlDelimiter Statement
hi! link markdownUrlTitle String
hi! link markdownUrlTitleDelimiter Delimiter
hi! link objcClass Type
hi! link objcDirective rubyClass
hi! link objcMessageName Identifier
hi! link objcMethodArg Normal
hi! link objcMethodName Identifier
hi! link objcStatement Constant
hi! link objcSubclass Type
hi! link objcSuperclass Type
hi! link phpArrayPair Structure
hi! link phpBoolean Constant
hi! link phpFunctions Function
hi! link phpNull Constant
hi! link phpOperator Normal
hi! link phpQuoteDouble StringDelimiter
hi! link phpQuoteSingle StringDelimiter
hi! link phpRelation Normal
hi! link phpSuperglobal Identifier
hi! link phpVarSelector Identifier
hi! link plug1 Title
hi! link plug2 Statement
hi! link plugBracket Structure
hi! link plugDash Special
hi! link plugDeleted Ignore
hi! link plugEdge PreProc
hi! link plugError ErrorMsg
hi! link plugH2 Type
hi! link plugInstall Function
hi! link plugMessage Function
hi! link plugName Statement
hi! link plugNotLoaded Comment
hi! link plugNumber Constant
hi! link plugPlus Constant
hi! link plugRelDate Comment
hi! link plugSha Identifier
hi! link plugStar Constant
hi! link plugTag Constant
hi! link plugUpdate Type
hi! link plugX Statement
hi! link pythonAsync Statement
hi! link pythonBuiltin Function
hi! link pythonComment Comment
hi! link pythonConditional Statement
hi! link pythonDecorator PreProc
hi! link pythonDecoratorName Function
hi! link pythonDoctest Special
hi! link pythonDoctestValue PreProc
hi! link pythonEscape Special
hi! link pythonException Statement
hi! link pythonExceptions Structure
hi! link pythonFunction Function
hi! link pythonInclude PreProc
hi! link pythonNumber Constant
hi! link pythonOperator Statement
hi! link pythonQuotes String
hi! link pythonRawString String
hi! link pythonRepeat Statement
hi! link pythonStatement Statement
hi! link pythonString String
hi! link pythonTodo Todo
hi! link pythonTripleQuotes String
hi! link qfError ErrorMsg
hi! link qfFileName Directory
hi! link qfLineNr LineNr
hi! link rubyConstant Type
hi! link rubyFunction Function
hi! link rubyGlobalVariable rubyInstanceVariable
hi! link rubyInterpolationDelimiter Identifier
hi! link rubyModule rubyClass
hi! link rubySharpBang Comment
hi! link rubyString String
hi! link rubyStringDelimiter StringDelimiter
hi! link shAlias Identifier
hi! link shArithRegion PreProc
hi! link shArithmetic Special
hi! link shAstQuote String
hi! link shAtExpr Identifier
hi! link shBQComment Comment
hi! link shBeginHere Structure
hi! link shBkslshDblQuote String
hi! link shBkslshSnglQuote String
hi! link shCaseBar Statement
hi! link shCaseCommandSub Special
hi! link shCaseDoubleQuote String
hi! link shCaseError ErrorMsg
hi! link shCaseIn Statement
hi! link shCaseSingleQuote String
hi! link shCaseStart Statement
hi! link shCharClass Identifier
hi! link shCmdSubRegion PreProc
hi! link shColon Comment
hi! link shCommandSub Special
hi! link shCommandSubBQ Special
hi! link shComment Comment
hi! link shCondError ErrorMsg
hi! link shConditional Statement
hi! link shCtrlSeq Special
hi! link shCurlyError ErrorMsg
hi! link shDTestError ErrorMsg
hi! link shDeref PreProc
hi! link shDerefDelim Structure
hi! link shDerefOp Structure
hi! link shDerefOpError ErrorMsg
hi! link shDerefPOL Structure
hi! link shDerefPPS Structure
hi! link shDerefPSR Structure
hi! link shDerefSimple PreProc
hi! link shDerefSpecial PreProc
hi! link shDerefString String
hi! link shDerefVar PreProc
hi! link shDerefWordError ErrorMsg
hi! link shDoError ErrorMsg
hi! link shDoubleQuote String
hi! link shEcho String
hi! link shEchoDelim Structure
hi! link shEchoQuote String
hi! link shEmbeddedEcho String
hi! link shEsacError ErrorMsg
hi! link shEscape Special
hi! link shExDoubleQuote String
hi! link shExSingleQuote String
hi! link shExprRegion Delimiter
hi! link shForPP Statement
hi! link shFunction Function
hi! link shFunctionKey Function
hi! link shFunctionName Function
hi! link shHereDoc String
hi! link shHereDoc01 Structure
hi! link shHereDoc02 Structure
hi! link shHereDoc03 Structure
hi! link shHereDoc04 Structure
hi! link shHereDoc05 Structure
hi! link shHereDoc06 Structure
hi! link shHereDoc07 Structure
hi! link shHereDoc08 Structure
hi! link shHereDoc09 Structure
hi! link shHereDoc10 Structure
hi! link shHereDoc11 Structure
hi! link shHereDoc12 Structure
hi! link shHereDoc13 Structure
hi! link shHereDoc14 Structure
hi! link shHereDoc15 Structure
hi! link shHereDoc16 Structure
hi! link shHerePayload String
hi! link shHereString Structure
hi! link shIfError ErrorMsg
hi! link shInError ErrorMsg
hi! link shLoop Statement
hi! link shNoQuote String
hi! link shNumber Constant
hi! link shOperator Structure
hi! link shOption Special
hi! link shParen Special
hi! link shParenError ErrorMsg
hi! link shPattern String
hi! link shPosnParm PreProc
hi! link shQuickComment Comment
hi! link shQuote Structure
hi! link shRange Structure
hi! link shRedir Structure
hi! link shRepeat Statement
hi! link shSet Statement
hi! link shSetList Identifier
hi! link shSetListDelim Structure
hi! link shSetOption Special
hi! link shShellVariables PreProc
hi! link shSingleQuote String
hi! link shSnglCase Statement
hi! link shSource Structure
hi! link shSpecial Special
hi! link shSpecialDQ Special
hi! link shSpecialNoZS Special
hi! link shSpecialNxt Special
hi! link shSpecialSQ Special
hi! link shSpecialStart Special
hi! link shStatement Statement
hi! link shString String
hi! link shStringSpecial Special
hi! link shSubShRegion Structure
hi! link shTestDoubleQuote String
hi! link shTestError ErrorMsg
hi! link shTestOpr Statement
hi! link shTestPattern String
hi! link shTestSingleQuote String
hi! link shTodo Todo
hi! link shTouchCmd Statement
hi! link shVariable Identifier
hi! link shWrapLineOperator Structure
hi! link sqlComment Comment
hi! link sqlFunction Function
hi! link sqlKeyword Special
hi! link sqlNumber Constant
hi! link sqlOperator Statement
hi! link sqlSpecial Special
hi! link sqlStatement Statement
hi! link sqlString String
hi! link sqlTodo Todo
hi! link sqlType Type
hi! link vbBoolean Constant
hi! link vbComment Comment
hi! link vbConditional Statement
hi! link vbConst Constant
hi! link vbDefine Constant
hi! link vbError ErrorMsg
hi! link vbEvents Special
hi! link vbFloat Constant
hi! link vbFunction Identifier
hi! link vbIdentifier Identifier
hi! link vbKeyword Statement
hi! link vbLineLabel Comment
hi! link vbLineNumber Comment
hi! link vbMethods PreProc
hi! link vbNumber Constant
hi! link vbOperator Structure
hi! link vbPreProc PreProc
hi! link vbRepeat Statement
hi! link vbStatement Statement
hi! link vbString String
hi! link vbTodo Todo
hi! link vbTypeSpecifier Type
hi! link vbTypes Type
hi! link vim9Comment Comment
hi! link vim9LineComment Comment
hi! link vimAbb Statement
hi! link vimAddress Constant
hi! link vimAuHighlight Statement
hi! link vimAugroupError ErrorMsg
hi! link vimAugroupKey Statement
hi! link vimAutoCmd Statement
hi! link vimAutoCmdMod Special
hi! link vimAutoCmdOpt PreProc
hi! link vimAutoEvent Type
hi! link vimAutoSet Statement
hi! link vimBehave Statement
hi! link vimBehaveError ErrorMsg
hi! link vimBehaveModel Statement
hi! link vimBracket Delimiter
hi! link vimBufnrWarn WarningMsg
hi! link vimCmplxRepeat Special
hi! link vimCollClassErr ErrorMsg
hi! link vimCommand Statement
hi! link vimComment Comment
hi! link vimCommentString String
hi! link vimCommentTitle PreProc
hi! link vimCondHL Statement
hi! link vimContinue Special
hi! link vimCtrlChar Special
hi! link vimEchoHL Statement
hi! link vimEchoHLNone Type
hi! link vimElseIfErr ErrorMsg
hi! link vimElseif Statement
hi! link vimEmbedError ErrorMsg
hi! link vimEnvvar PreProc
hi! link vimErrSetting ErrorMsg
hi! link vimError ErrorMsg
hi! link vimEscape Special
hi! link vimFBVar Identifier
hi! link vimFTCmd Statement
hi! link vimFTError ErrorMsg
hi! link vimFTOption Type
hi! link vimFgBgAttrib PreProc
hi! link vimFold Folded
hi! link vimFunc ErrorMsg
hi! link vimFuncEcho Statement
hi! link vimFuncKey Statement
hi! link vimFuncName Function
hi! link vimFuncSID Special
hi! link vimFuncVar Identifier
hi! link vimFunctionError ErrorMsg
hi! link vimGroup Type
hi! link vimGroupAdd Special
hi! link vimGroupName Type
hi! link vimGroupRem Special
hi! link vimGroupSpecial Special
hi! link vimHLGroup Type
hi! link vimHLMod PreProc
hi! link vimHiAttrib PreProc
hi! link vimHiAttribList ErrorMsg
hi! link vimHiCTerm Type
hi! link vimHiClear Statement
hi! link vimHiCtermError ErrorMsg
hi! link vimHiCtermFgBg Type
hi! link vimHiCtermul Type
hi! link vimHiGroup Type
hi! link vimHiGui Type
hi! link vimHiGuiFgBg Type
hi! link vimHiGuiFont Type
hi! link vimHiGuiRgb Constant
hi! link vimHiKeyError ErrorMsg
hi! link vimHiNmbr Constant
hi! link vimHiStartStop Type
hi! link vimHiTerm Type
hi! link vimHighlight Statement
hi! link vimInsert String
hi! link vimIskSep Delimiter
hi! link vimKeyCode Identifier
hi! link vimKeyCodeError ErrorMsg
hi! link vimKeyword Statement
hi! link vimLet Statement
hi! link vimLetHereDoc String
hi! link vimLetHereDocStart Special
hi! link vimLetHereDocStop Special
hi! link vimLineComment Comment
hi! link vimMap Statement
hi! link vimMapBang Statement
hi! link vimMapMod Delimiter
hi! link vimMapModErr ErrorMsg
hi! link vimMapModKey Special
hi! link vimMark Constant
hi! link vimMarkNumber Constant
hi! link vimMenuMod Delimiter
hi! link vimMenuName PreProc
hi! link vimMenuNameMore PreProc
hi! link vimMtchComment Comment
hi! link vimNorm Statement
hi! link vimNotFunc Statement
hi! link vimNotPatSep String
hi! link vimNotation Special
hi! link vimNumber Constant
hi! link vimOper Normal
hi! link vimOperError ErrorMsg
hi! link vimOption PreProc
hi! link vimParenSep Delimiter
hi! link vimPatSep Special
hi! link vimPatSepErr ErrorMsg
hi! link vimPatSepR Special
hi! link vimPatSepZ Special
hi! link vimPatSepZone String
hi! link vimPattern Type
hi! link vimPlainMark Constant
hi! link vimPlainRegister Special
hi! link vimRegister Special
hi! link vimScriptDelim Comment
hi! link vimSearch String
hi! link vimSearchDelim Statement
hi! link vimSep Delimiter
hi! link vimSetMod PreProc
hi! link vimSetSep Statement
hi! link vimSetString String
hi! link vimSpecFile Identifier
hi! link vimSpecFileMod Identifier
hi! link vimSpecial Type
hi! link vimStatement Statement
hi! link vimString String
hi! link vimStringCont String
hi! link vimStringEnd String
hi! link vimSubst Statement
hi! link vimSubst1 Statement
hi! link vimSubstDelim Delimiter
hi! link vimSubstFlagErr ErrorMsg
hi! link vimSubstFlags Special
hi! link vimSubstSubstr Special
hi! link vimSubstTwoBS String
hi! link vimSynCase Type
hi! link vimSynCaseError ErrorMsg
hi! link vimSynContains Special
hi! link vimSynError ErrorMsg
hi! link vimSynKeyContainedin Special
hi! link vimSynKeyOpt Special
hi! link vimSynMtchGrp Special
hi! link vimSynMtchOpt Special
hi! link vimSynNextgroup Special
hi! link vimSynNotPatRange String
hi! link vimSynOption Special
hi! link vimSynPatRange String
hi! link vimSynReg Type
hi! link vimSynRegOpt Special
hi! link vimSynRegPat String
hi! link vimSynType Type
hi! link vimSyncC Type
hi! link vimSyncError ErrorMsg
hi! link vimSyncGroup Type
hi! link vimSyncGroupName Type
hi! link vimSyncKey Type
hi! link vimSyncNone Type
hi! link vimSyntax Statement
hi! link vimTodo Todo
hi! link vimType Type
hi! link vimUnmap Statement
hi! link vimUserAttrb Type
hi! link vimUserAttrbCmplt Type
hi! link vimUserAttrbCmpltFunc Special
hi! link vimUserAttrbError ErrorMsg
hi! link vimUserAttrbKey PreProc
hi! link vimUserCmdError ErrorMsg
hi! link vimUserCommand Statement
hi! link vimUserFunc Normal
hi! link vimVar Identifier
hi! link vimWarn WarningMsg
hi! link vimoperStar Normal
hi! link xmlAttrib Type
hi! link xmlAttribPunct Comment
hi! link xmlCdata String
hi! link xmlCdataCdata Statement
hi! link xmlCdataEnd Type
hi! link xmlCdataStart Type
hi! link xmlComment Comment
hi! link xmlCommentError ErrorMsg
hi! link xmlCommentPart Comment
hi! link xmlCommentStart Comment
hi! link xmlDocTypeDecl PreProc
hi! link xmlDocTypeKeyword PreProc
hi! link xmlEndTag Statement
hi! link xmlEntity Special
hi! link xmlEntityPunct Special
hi! link xmlEqual Statement
hi! link xmlError ErrorMsg
hi! link xmlInlineDTD Function
hi! link xmlNamespace Special
hi! link xmlProcessing Type
hi! link xmlProcessingDelim Type
hi! link xmlString String
hi! link xmlTag Statement
hi! link xmlTagName Statement
hi! link xmlTodo Todo

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#414141', '#e87174', '#93b97e', '#ffb981', '#648699', '#e1c0f6', '#00988e', '#dedede', '#bdbdbd', '#ffa0a2', '#b8bb26', '#ffdba5', '#abd9f3', '#fbdafc', '#00b3a8', '#fefefe']
endif
hi Normal guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi ColorColumn guifg=#e8e8d3 guibg=#000000 gui=NONE cterm=NONE
hi ColortemplateInfoBg guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi ColortemplateInfoBlack guifg=#e8e8d3 guibg=#000000 gui=NONE cterm=NONE
hi ColortemplateInfoFg guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi ColortemplateInfoSp guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi Comment guifg=#888888 guibg=#1e1e1e gui=NONE cterm=NONE
hi Constant guifg=#cf6a4c guibg=#1e1e1e gui=NONE cterm=NONE
hi Cursor guifg=#1e1e1e guibg=#b0d0f0 gui=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#3E3D32 gui=NONE cterm=NONE
hi CursorLine guifg=#e8e8d3 guibg=#1c1c1c gui=NONE cterm=NONE
hi CursorLineNr guifg=#ccc5c4 guibg=#1e1e1e gui=NONE cterm=NONE
hi DbgBreakPt guifg=#e8e8d3 guibg=#4f0037 gui=NONE cterm=NONE
hi DbgCurrent guifg=#deebfe guibg=#345fa8 gui=NONE cterm=NONE
hi Delimiter guifg=#668799 guibg=#1e1e1e gui=NONE cterm=NONE
hi DiffAdd guifg=#d2ebbe guibg=#437019 gui=NONE cterm=NONE
hi DiffChange guifg=#e8e8d3 guibg=#2b5b77 gui=NONE cterm=NONE
hi DiffDelete guifg=#40000a guibg=#700009 gui=NONE cterm=NONE
hi DiffText guifg=#8fbfdc guibg=#000000 gui=reverse cterm=reverse
hi Directory guifg=#dad085 guibg=#1e1e1e gui=NONE cterm=NONE
hi ErrorMsg guifg=#e8e8d3 guibg=#902020 gui=NONE cterm=NONE
hi ExtraWhitespace guifg=#e8e8d3 guibg=#888888 gui=NONE cterm=NONE
hi FoldColumn guifg=#535d66 guibg=#1f1f1f gui=NONE cterm=NONE
hi Folded guifg=#a0a8b0 guibg=#384048 gui=NONE cterm=NONE
hi Function guifg=#fad07a guibg=#1e1e1e gui=NONE cterm=NONE
hi Identifier guifg=#c6b6ee guibg=#1e1e1e gui=NONE cterm=NONE
hi Ignore guifg=#1e1e1e guibg=#1e1e1e gui=NONE cterm=NONE
hi IncSearch guifg=#e8e8d3 guibg=#1e1e1e gui=reverse cterm=reverse
hi IndentGuidesEven guifg=#e8e8d3 guibg=#1b1b1b gui=NONE cterm=NONE
hi IndentGuidesOdd guifg=#e8e8d3 guibg=#232323 gui=NONE cterm=NONE
hi LineNr guifg=#605958 guibg=#1e1e1e gui=NONE cterm=NONE
hi LineNrAbove guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi LineNrBelow guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi MatchParen guifg=#ffffff guibg=#556779 gui=bold cterm=bold
hi ModeMsg guifg=#e8e8d3 guibg=#1e1e1e gui=bold cterm=bold
hi NERDTreeFile guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi NERDTreeLink guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi NERDTreeNodeDelimiters guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi Noise guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi NonText guifg=#465457 guibg=#1e1e1e gui=NONE cterm=NONE
hi None guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi Pmenu guifg=#ffffff guibg=#606060 gui=NONE cterm=NONE
hi PmenuSbar guifg=#e8e8d3 guibg=#bebebe gui=NONE cterm=NONE
hi PmenuSel guifg=#101010 guibg=#eeeeee gui=NONE cterm=NONE
hi PmenuThumb guifg=#e8e8d3 guibg=#ffffff gui=NONE cterm=NONE
hi PreProc guifg=#8fbfdc guibg=#1e1e1e gui=NONE cterm=NONE
hi PreciseJumpTarget guifg=#b9ed67 guibg=#405026 gui=NONE cterm=NONE
hi Question guifg=#65c254 guibg=#1e1e1e gui=NONE cterm=NONE
hi Search guifg=#f0a0c0 guibg=#302028 gui=underline cterm=underline
hi SignColumn guifg=#777777 guibg=#333333 gui=NONE cterm=NONE
hi Special guifg=#cc8bc9 guibg=#1e1e1e gui=NONE cterm=NONE
hi SpecialKey guifg=#465457 guibg=#1c1c1c gui=NONE cterm=NONE
hi SpellBad guifg=#e8e8d3 guibg=#902020 guisp=#ff0000 gui=underline cterm=underline
hi SpellCap guifg=#e8e8d3 guibg=#0000df guisp=#0000ff gui=underline cterm=underline
hi SpellLocal guifg=#e8e8d3 guibg=#2d7067 guisp=#00ffff gui=underline cterm=underline
hi SpellRare guifg=#e8e8d3 guibg=#540063 guisp=#ff00ff gui=underline cterm=underline
hi Statement guifg=#8197bf guibg=#1e1e1e gui=NONE cterm=NONE
hi StatusLine guifg=#000000 guibg=#dddddd gui=NONE cterm=NONE
hi StatusLineNC guifg=#ffffff guibg=#403c41 gui=NONE cterm=NONE
hi StatusLineTerm guifg=#1e1e1e guibg=#90ee90 gui=bold cterm=bold
hi StatusLineTermNC guifg=#1e1e1e guibg=#90ee90 gui=NONE cterm=NONE
hi StorageClass guifg=#c59f6f guibg=#1e1e1e gui=NONE cterm=NONE
hi String guifg=#99ad6a guibg=#1e1e1e gui=NONE cterm=NONE
hi StringDelim guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi StringDelimiter guifg=#556633 guibg=#1e1e1e gui=NONE cterm=NONE
hi Structure guifg=#8fbfdc guibg=#1e1e1e gui=NONE cterm=NONE
hi TabLine guifg=#000000 guibg=#b0b8c0 gui=NONE cterm=NONE
hi TabLineFill guifg=#9098a0 guibg=#1e1e1e gui=NONE cterm=NONE
hi TabLineSel guifg=#000000 guibg=#f0f0f0 gui=bold cterm=bold
hi Title guifg=#70b950 guibg=#1e1e1e gui=bold cterm=bold
hi Todo guifg=#c7c7c7 guibg=#1e1e1e gui=bold cterm=bold
hi ToolbarButton guifg=#000000 guibg=#d3d3d3 gui=bold cterm=bold
hi ToolbarLine guifg=#e8e8d3 guibg=#7f7f7f gui=NONE cterm=NONE
hi Type guifg=#ffb964 guibg=#1e1e1e gui=NONE cterm=NONE
hi Underlined guifg=#80a0ff guibg=#1e1e1e gui=underline cterm=underline
hi VertSplit guifg=#777777 guibg=#403c41 gui=NONE cterm=NONE
hi Visual guifg=#e8e8d3 guibg=#264F78 gui=NONE cterm=NONE
hi VisualNOS guifg=#e8e8d3 guibg=#1e1e1e gui=bold,underline cterm=bold,underline
hi WarningMsg guifg=#ff0000 guibg=#1e1e1e gui=NONE cterm=NONE
hi WildMenu guifg=#f0a0c0 guibg=#302028 gui=NONE cterm=NONE
hi bashSpecialVariables guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi bashStatement guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi colortemplateAux guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi colortemplateColorDef guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi colortemplateColorSpec guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi colortemplateCompound guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi colortemplateHelp guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi colortemplateReset guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi colortemplateVim guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssAttrRegion guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssDefinition guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssLength guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssMathGroup guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssMathParens guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssPseudoClass guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssPseudoClassFn guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssSpecialCharQ guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssSpecialCharQQ guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssString guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi cssStyle guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi fzf1 guifg=#e12672 guibg=#565656 gui=NONE cterm=NONE
hi fzf2 guifg=#bcddbd guibg=#565656 gui=NONE cterm=NONE
hi fzf3 guifg=#d9d9d9 guibg=#565656 gui=NONE cterm=NONE
hi helpGraphic guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi helpLeadBlank guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi helpNormal guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi htmlBold guifg=#e8e8d3 guibg=#1e1e1e gui=bold cterm=bold
hi htmlBoldItalic guifg=#e8e8d3 guibg=#1e1e1e gui=bold,italic cterm=bold,italic
hi htmlBoldUnderline guifg=#e8e8d3 guibg=#1e1e1e gui=bold,underline cterm=bold,underline
hi htmlBoldUnderlineItalic guifg=#e8e8d3 guibg=#1e1e1e gui=bold,italic,underline cterm=bold,italic,underline
hi htmlItalic guifg=#e8e8d3 guibg=#1e1e1e gui=italic cterm=italic
hi htmlMath guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi htmlStrike guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi htmlSvg guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi htmlTagN guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi htmlUnderline guifg=#e8e8d3 guibg=#1e1e1e gui=underline cterm=underline
hi htmlUnderlineItalic guifg=#e8e8d3 guibg=#1e1e1e gui=italic,underline cterm=italic,underline
hi javaScriptCommentSkip guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi javaScriptParens guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi lCursor guifg=#1e1e1e guibg=#e8e8d3 gui=NONE cterm=NONE
hi markdownCode guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownCodeBlock guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownHighlighthtml guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownHighlightpython guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownHighlightsh guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownHighlightsql guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownLineBreak guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownLineStart guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownLink guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownLinkDelimiter guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownLinkTextDelimiter guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi markdownValid guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi plugCommit guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi pythonAttribute guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi pythonMatrixMultiply guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi pythonSpaceError guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi pythonSync guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi qfSeparator guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi rubyClass guifg=#447799 guibg=#1e1e1e gui=NONE cterm=NONE
hi rubyControl guifg=#7597c6 guibg=#1e1e1e gui=NONE cterm=NONE
hi rubyIdentifier guifg=#c6b6fe guibg=#1e1e1e gui=NONE cterm=NONE
hi rubyInstanceVariable guifg=#c6b6fe guibg=#1e1e1e gui=NONE cterm=NONE
hi rubyPredefinedIdentifier guifg=#de5577 guibg=#1e1e1e gui=NONE cterm=NONE
hi rubyRegexp guifg=#dd0093 guibg=#1e1e1e gui=NONE cterm=NONE
hi rubyRegexpDelimiter guifg=#540063 guibg=#1e1e1e gui=NONE cterm=NONE
hi rubyRegexpSpecial guifg=#a40073 guibg=#1e1e1e gui=NONE cterm=NONE
hi rubySymbol guifg=#7697d6 guibg=#1e1e1e gui=NONE cterm=NONE
hi shArithParen guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shCase guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shCaseEsac guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shCaseEsacSync guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shCaseExSingleQuote guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shCaseLabel guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shCaseRange guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shCmdParenRegion guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shComma guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shCurlyIn guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDblBrace guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDblParen guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDerefEscape guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDerefLen guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDerefOffset guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDerefPPSleft guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDerefPPSright guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDerefPSRleft guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDerefPSRright guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDerefPattern guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDerefVarArray guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDo guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shDoSync guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shEchoDeref guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shExpr guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shFor guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shForSync guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shFunctionFour guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shFunctionOne guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shFunctionStart guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shFunctionThree guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shFunctionTwo guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shIf guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shIfSync guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shOK guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shSkipInitWS guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shSpecialVar guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shSubSh guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shTest guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shTouch guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shUntilSync guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shVar guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shVarAssign guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi shWhileSync guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi sqlFold guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimAuSyntax guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimAugroup guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimAugroupSyncA guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimAutoCmdSfxList guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimAutoCmdSpace guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimAutoEventList guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimClusterName guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimCmdSep guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimCollClass guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimCollection guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimComFilter guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimCommentTitleLeader guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimEcho guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimEscapeBrace guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimExecute guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimExtCmd guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimFiletype guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimFilter guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimFuncBlank guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimFuncBody guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimFunction guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimGlobal guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimGroupList guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimHiBang guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimHiCtermColor guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimHiFontname guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimHiGuiFontname guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimHiKeyList guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimHiLink guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimHiTermcap guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimIsCommand guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimIskList guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimMapLhs guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimMapRhs guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimMapRhsExtend guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimMenuBang guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimMenuMap guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimMenuPriority guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimMenuRhs guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimNormCmds guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimOperParen guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimPatRegion guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimPythonRegion guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimRange guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimRegion guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSet guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSetEqual guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimStdPlugin guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSubst2 guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSubstPat guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSubstRange guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSubstRep guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSubstRep4 guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSynKeyRegion guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSynLine guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSynMatchRegion guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSynMtchCchar guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSynMtchGroup guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSynPatMod guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSynRegion guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSyncLinebreak guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSyncLinecont guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSyncLines guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSyncMatch guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimSyncRegion guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimUserCmd guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi vimUsrCmd guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi xmlDocType guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi xmlRegion guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
hi xmlSyncComment guifg=#e8e8d3 guibg=#1e1e1e gui=NONE cterm=NONE
if !s:italics
  hi htmlBoldItalic gui=bold cterm=bold
  hi htmlBoldUnderlineItalic gui=bold,underline cterm=bold,underline
  hi htmlItalic gui=NONE cterm=NONE
  hi htmlUnderlineItalic gui=underline cterm=underline
endif

if s:t_Co >= 256
  hi Normal ctermfg=187 ctermbg=234 cterm=NONE
  hi ColorColumn ctermfg=187 ctermbg=16 cterm=NONE
  hi ColortemplateInfoBg ctermfg=187 ctermbg=234 cterm=NONE
  hi ColortemplateInfoBlack ctermfg=187 ctermbg=16 cterm=NONE
  hi ColortemplateInfoFg ctermfg=187 ctermbg=234 cterm=NONE
  hi ColortemplateInfoSp ctermfg=187 ctermbg=234 cterm=NONE
  hi Comment ctermfg=102 ctermbg=234 cterm=NONE
  hi Constant ctermfg=173 ctermbg=234 cterm=NONE
  hi Cursor ctermfg=234 ctermbg=153 cterm=NONE
  hi CursorColumn ctermfg=187 ctermbg=234 cterm=NONE
  hi CursorLine ctermfg=187 ctermbg=234 cterm=NONE
  hi CursorLineNr ctermfg=251 ctermbg=234 cterm=NONE
  hi DbgBreakPt ctermfg=187 ctermbg=53 cterm=NONE
  hi DbgCurrent ctermfg=255 ctermbg=25 cterm=NONE
  hi Delimiter ctermfg=67 ctermbg=234 cterm=NONE
  hi DiffAdd ctermfg=194 ctermbg=22 cterm=NONE
  hi DiffChange ctermfg=187 ctermbg=24 cterm=NONE
  hi DiffDelete ctermfg=52 ctermbg=52 cterm=NONE
  hi DiffText ctermfg=74 ctermbg=16 cterm=reverse
  hi Directory ctermfg=186 ctermbg=234 cterm=NONE
  hi ErrorMsg ctermfg=187 ctermbg=88 cterm=NONE
  hi ExtraWhitespace ctermfg=187 ctermbg=102 cterm=NONE
  hi FoldColumn ctermfg=59 ctermbg=234 cterm=NONE
  hi Folded ctermfg=248 ctermbg=238 cterm=NONE
  hi Function ctermfg=222 ctermbg=234 cterm=NONE
  hi Identifier ctermfg=183 ctermbg=234 cterm=NONE
  hi Ignore ctermfg=234 ctermbg=234 cterm=NONE
  hi IncSearch ctermfg=187 ctermbg=234 cterm=reverse
  hi IndentGuidesEven ctermfg=187 ctermbg=234 cterm=NONE
  hi IndentGuidesOdd ctermfg=187 ctermbg=235 cterm=NONE
  hi LineNr ctermfg=240 ctermbg=234 cterm=NONE
  hi LineNrAbove ctermfg=187 ctermbg=234 cterm=NONE
  hi LineNrBelow ctermfg=187 ctermbg=234 cterm=NONE
  hi MatchParen ctermfg=231 ctermbg=241 cterm=bold
  hi ModeMsg ctermfg=187 ctermbg=234 cterm=bold
  hi NERDTreeFile ctermfg=187 ctermbg=234 cterm=NONE
  hi NERDTreeLink ctermfg=187 ctermbg=234 cterm=NONE
  hi NERDTreeNodeDelimiters ctermfg=187 ctermbg=234 cterm=NONE
  hi Noise ctermfg=187 ctermbg=234 cterm=NONE
  hi NonText ctermfg=239 ctermbg=234 cterm=NONE
  hi None ctermfg=187 ctermbg=234 cterm=NONE
  hi Pmenu ctermfg=231 ctermbg=59 cterm=NONE
  hi PmenuSbar ctermfg=187 ctermbg=250 cterm=NONE
  hi PmenuSel ctermfg=233 ctermbg=255 cterm=NONE
  hi PmenuThumb ctermfg=187 ctermbg=231 cterm=NONE
  hi PreProc ctermfg=74 ctermbg=234 cterm=NONE
  hi PreciseJumpTarget ctermfg=155 ctermbg=22 cterm=NONE
  hi Question ctermfg=77 ctermbg=234 cterm=NONE
  hi Search ctermfg=218 ctermbg=235 cterm=underline
  hi SignColumn ctermfg=243 ctermbg=236 cterm=NONE
  hi Special ctermfg=176 ctermbg=234 cterm=NONE
  hi SpecialKey ctermfg=239 ctermbg=234 cterm=NONE
  hi SpellBad ctermfg=187 ctermbg=88 cterm=underline
  hi SpellCap ctermfg=187 ctermbg=20 cterm=underline
  hi SpellLocal ctermfg=187 ctermbg=23 cterm=underline
  hi SpellRare ctermfg=187 ctermbg=53 cterm=underline
  hi Statement ctermfg=103 ctermbg=234 cterm=NONE
  hi StatusLine ctermfg=16 ctermbg=253 cterm=NONE
  hi StatusLineNC ctermfg=231 ctermbg=237 cterm=NONE
  hi StatusLineTerm ctermfg=234 ctermbg=120 cterm=bold
  hi StatusLineTermNC ctermfg=234 ctermbg=120 cterm=NONE
  hi StorageClass ctermfg=180 ctermbg=234 cterm=NONE
  hi String ctermfg=107 ctermbg=234 cterm=NONE
  hi StringDelim ctermfg=187 ctermbg=234 cterm=NONE
  hi StringDelimiter ctermfg=58 ctermbg=234 cterm=NONE
  hi Structure ctermfg=74 ctermbg=234 cterm=NONE
  hi TabLine ctermfg=16 ctermbg=250 cterm=NONE
  hi TabLineFill ctermfg=246 ctermbg=234 cterm=NONE
  hi TabLineSel ctermfg=16 ctermbg=255 cterm=bold
  hi Title ctermfg=71 ctermbg=234 cterm=bold
  hi Todo ctermfg=251 ctermbg=234 cterm=bold
  hi ToolbarButton ctermfg=16 ctermbg=252 cterm=bold
  hi ToolbarLine ctermfg=187 ctermbg=244 cterm=NONE
  hi Type ctermfg=215 ctermbg=234 cterm=NONE
  hi Underlined ctermfg=111 ctermbg=234 cterm=underline
  hi VertSplit ctermfg=243 ctermbg=237 cterm=NONE
  hi Visual ctermfg=187 ctermbg=238 cterm=NONE
  hi VisualNOS ctermfg=187 ctermbg=234 cterm=bold,underline
  hi WarningMsg ctermfg=196 ctermbg=234 cterm=NONE
  hi WildMenu ctermfg=218 ctermbg=235 cterm=NONE
  hi bashSpecialVariables ctermfg=187 ctermbg=234 cterm=NONE
  hi bashStatement ctermfg=187 ctermbg=234 cterm=NONE
  hi colortemplateAux ctermfg=187 ctermbg=234 cterm=NONE
  hi colortemplateColorDef ctermfg=187 ctermbg=234 cterm=NONE
  hi colortemplateColorSpec ctermfg=187 ctermbg=234 cterm=NONE
  hi colortemplateCompound ctermfg=187 ctermbg=234 cterm=NONE
  hi colortemplateHelp ctermfg=187 ctermbg=234 cterm=NONE
  hi colortemplateReset ctermfg=187 ctermbg=234 cterm=NONE
  hi colortemplateVim ctermfg=187 ctermbg=234 cterm=NONE
  hi cssAttrRegion ctermfg=187 ctermbg=234 cterm=NONE
  hi cssDefinition ctermfg=187 ctermbg=234 cterm=NONE
  hi cssLength ctermfg=187 ctermbg=234 cterm=NONE
  hi cssMathGroup ctermfg=187 ctermbg=234 cterm=NONE
  hi cssMathParens ctermfg=187 ctermbg=234 cterm=NONE
  hi cssPseudoClass ctermfg=187 ctermbg=234 cterm=NONE
  hi cssPseudoClassFn ctermfg=187 ctermbg=234 cterm=NONE
  hi cssSpecialCharQ ctermfg=187 ctermbg=234 cterm=NONE
  hi cssSpecialCharQQ ctermfg=187 ctermbg=234 cterm=NONE
  hi cssString ctermfg=187 ctermbg=234 cterm=NONE
  hi cssStyle ctermfg=187 ctermbg=234 cterm=NONE
  hi fzf1 ctermfg=161 ctermbg=240 cterm=NONE
  hi fzf2 ctermfg=151 ctermbg=240 cterm=NONE
  hi fzf3 ctermfg=253 ctermbg=240 cterm=NONE
  hi helpGraphic ctermfg=187 ctermbg=234 cterm=NONE
  hi helpLeadBlank ctermfg=187 ctermbg=234 cterm=NONE
  hi helpNormal ctermfg=187 ctermbg=234 cterm=NONE
  hi htmlBold ctermfg=187 ctermbg=234 cterm=bold
  hi htmlBoldItalic ctermfg=187 ctermbg=234 cterm=bold,italic
  hi htmlBoldUnderline ctermfg=187 ctermbg=234 cterm=bold,underline
  hi htmlBoldUnderlineItalic ctermfg=187 ctermbg=234 cterm=bold,italic,underline
  hi htmlItalic ctermfg=187 ctermbg=234 cterm=italic
  hi htmlMath ctermfg=187 ctermbg=234 cterm=NONE
  hi htmlStrike ctermfg=187 ctermbg=234 cterm=NONE
  hi htmlSvg ctermfg=187 ctermbg=234 cterm=NONE
  hi htmlTagN ctermfg=187 ctermbg=234 cterm=NONE
  hi htmlUnderline ctermfg=187 ctermbg=234 cterm=underline
  hi htmlUnderlineItalic ctermfg=187 ctermbg=234 cterm=italic,underline
  hi javaScriptCommentSkip ctermfg=187 ctermbg=234 cterm=NONE
  hi javaScriptParens ctermfg=187 ctermbg=234 cterm=NONE
  hi lCursor ctermfg=234 ctermbg=187 cterm=NONE
  hi markdownCode ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownCodeBlock ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownHighlighthtml ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownHighlightpython ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownHighlightsh ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownHighlightsql ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownLineBreak ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownLineStart ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownLink ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownLinkDelimiter ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownLinkTextDelimiter ctermfg=187 ctermbg=234 cterm=NONE
  hi markdownValid ctermfg=187 ctermbg=234 cterm=NONE
  hi plugCommit ctermfg=187 ctermbg=234 cterm=NONE
  hi pythonAttribute ctermfg=187 ctermbg=234 cterm=NONE
  hi pythonMatrixMultiply ctermfg=187 ctermbg=234 cterm=NONE
  hi pythonSpaceError ctermfg=187 ctermbg=234 cterm=NONE
  hi pythonSync ctermfg=187 ctermbg=234 cterm=NONE
  hi qfSeparator ctermfg=187 ctermbg=234 cterm=NONE
  hi rubyClass ctermfg=31 ctermbg=234 cterm=NONE
  hi rubyControl ctermfg=67 ctermbg=234 cterm=NONE
  hi rubyIdentifier ctermfg=147 ctermbg=234 cterm=NONE
  hi rubyInstanceVariable ctermfg=147 ctermbg=234 cterm=NONE
  hi rubyPredefinedIdentifier ctermfg=168 ctermbg=234 cterm=NONE
  hi rubyRegexp ctermfg=162 ctermbg=234 cterm=NONE
  hi rubyRegexpDelimiter ctermfg=53 ctermbg=234 cterm=NONE
  hi rubyRegexpSpecial ctermfg=126 ctermbg=234 cterm=NONE
  hi rubySymbol ctermfg=68 ctermbg=234 cterm=NONE
  hi shArithParen ctermfg=187 ctermbg=234 cterm=NONE
  hi shCase ctermfg=187 ctermbg=234 cterm=NONE
  hi shCaseEsac ctermfg=187 ctermbg=234 cterm=NONE
  hi shCaseEsacSync ctermfg=187 ctermbg=234 cterm=NONE
  hi shCaseExSingleQuote ctermfg=187 ctermbg=234 cterm=NONE
  hi shCaseLabel ctermfg=187 ctermbg=234 cterm=NONE
  hi shCaseRange ctermfg=187 ctermbg=234 cterm=NONE
  hi shCmdParenRegion ctermfg=187 ctermbg=234 cterm=NONE
  hi shComma ctermfg=187 ctermbg=234 cterm=NONE
  hi shCurlyIn ctermfg=187 ctermbg=234 cterm=NONE
  hi shDblBrace ctermfg=187 ctermbg=234 cterm=NONE
  hi shDblParen ctermfg=187 ctermbg=234 cterm=NONE
  hi shDerefEscape ctermfg=187 ctermbg=234 cterm=NONE
  hi shDerefLen ctermfg=187 ctermbg=234 cterm=NONE
  hi shDerefOffset ctermfg=187 ctermbg=234 cterm=NONE
  hi shDerefPPSleft ctermfg=187 ctermbg=234 cterm=NONE
  hi shDerefPPSright ctermfg=187 ctermbg=234 cterm=NONE
  hi shDerefPSRleft ctermfg=187 ctermbg=234 cterm=NONE
  hi shDerefPSRright ctermfg=187 ctermbg=234 cterm=NONE
  hi shDerefPattern ctermfg=187 ctermbg=234 cterm=NONE
  hi shDerefVarArray ctermfg=187 ctermbg=234 cterm=NONE
  hi shDo ctermfg=187 ctermbg=234 cterm=NONE
  hi shDoSync ctermfg=187 ctermbg=234 cterm=NONE
  hi shEchoDeref ctermfg=187 ctermbg=234 cterm=NONE
  hi shExpr ctermfg=187 ctermbg=234 cterm=NONE
  hi shFor ctermfg=187 ctermbg=234 cterm=NONE
  hi shForSync ctermfg=187 ctermbg=234 cterm=NONE
  hi shFunctionFour ctermfg=187 ctermbg=234 cterm=NONE
  hi shFunctionOne ctermfg=187 ctermbg=234 cterm=NONE
  hi shFunctionStart ctermfg=187 ctermbg=234 cterm=NONE
  hi shFunctionThree ctermfg=187 ctermbg=234 cterm=NONE
  hi shFunctionTwo ctermfg=187 ctermbg=234 cterm=NONE
  hi shIf ctermfg=187 ctermbg=234 cterm=NONE
  hi shIfSync ctermfg=187 ctermbg=234 cterm=NONE
  hi shOK ctermfg=187 ctermbg=234 cterm=NONE
  hi shSkipInitWS ctermfg=187 ctermbg=234 cterm=NONE
  hi shSpecialVar ctermfg=187 ctermbg=234 cterm=NONE
  hi shSubSh ctermfg=187 ctermbg=234 cterm=NONE
  hi shTest ctermfg=187 ctermbg=234 cterm=NONE
  hi shTouch ctermfg=187 ctermbg=234 cterm=NONE
  hi shUntilSync ctermfg=187 ctermbg=234 cterm=NONE
  hi shVar ctermfg=187 ctermbg=234 cterm=NONE
  hi shVarAssign ctermfg=187 ctermbg=234 cterm=NONE
  hi shWhileSync ctermfg=187 ctermbg=234 cterm=NONE
  hi sqlFold ctermfg=187 ctermbg=234 cterm=NONE
  hi vimAuSyntax ctermfg=187 ctermbg=234 cterm=NONE
  hi vimAugroup ctermfg=187 ctermbg=234 cterm=NONE
  hi vimAugroupSyncA ctermfg=187 ctermbg=234 cterm=NONE
  hi vimAutoCmdSfxList ctermfg=187 ctermbg=234 cterm=NONE
  hi vimAutoCmdSpace ctermfg=187 ctermbg=234 cterm=NONE
  hi vimAutoEventList ctermfg=187 ctermbg=234 cterm=NONE
  hi vimClusterName ctermfg=187 ctermbg=234 cterm=NONE
  hi vimCmdSep ctermfg=187 ctermbg=234 cterm=NONE
  hi vimCollClass ctermfg=187 ctermbg=234 cterm=NONE
  hi vimCollection ctermfg=187 ctermbg=234 cterm=NONE
  hi vimComFilter ctermfg=187 ctermbg=234 cterm=NONE
  hi vimCommentTitleLeader ctermfg=187 ctermbg=234 cterm=NONE
  hi vimEcho ctermfg=187 ctermbg=234 cterm=NONE
  hi vimEscapeBrace ctermfg=187 ctermbg=234 cterm=NONE
  hi vimExecute ctermfg=187 ctermbg=234 cterm=NONE
  hi vimExtCmd ctermfg=187 ctermbg=234 cterm=NONE
  hi vimFiletype ctermfg=187 ctermbg=234 cterm=NONE
  hi vimFilter ctermfg=187 ctermbg=234 cterm=NONE
  hi vimFuncBlank ctermfg=187 ctermbg=234 cterm=NONE
  hi vimFuncBody ctermfg=187 ctermbg=234 cterm=NONE
  hi vimFunction ctermfg=187 ctermbg=234 cterm=NONE
  hi vimGlobal ctermfg=187 ctermbg=234 cterm=NONE
  hi vimGroupList ctermfg=187 ctermbg=234 cterm=NONE
  hi vimHiBang ctermfg=187 ctermbg=234 cterm=NONE
  hi vimHiCtermColor ctermfg=187 ctermbg=234 cterm=NONE
  hi vimHiFontname ctermfg=187 ctermbg=234 cterm=NONE
  hi vimHiGuiFontname ctermfg=187 ctermbg=234 cterm=NONE
  hi vimHiKeyList ctermfg=187 ctermbg=234 cterm=NONE
  hi vimHiLink ctermfg=187 ctermbg=234 cterm=NONE
  hi vimHiTermcap ctermfg=187 ctermbg=234 cterm=NONE
  hi vimIsCommand ctermfg=187 ctermbg=234 cterm=NONE
  hi vimIskList ctermfg=187 ctermbg=234 cterm=NONE
  hi vimMapLhs ctermfg=187 ctermbg=234 cterm=NONE
  hi vimMapRhs ctermfg=187 ctermbg=234 cterm=NONE
  hi vimMapRhsExtend ctermfg=187 ctermbg=234 cterm=NONE
  hi vimMenuBang ctermfg=187 ctermbg=234 cterm=NONE
  hi vimMenuMap ctermfg=187 ctermbg=234 cterm=NONE
  hi vimMenuPriority ctermfg=187 ctermbg=234 cterm=NONE
  hi vimMenuRhs ctermfg=187 ctermbg=234 cterm=NONE
  hi vimNormCmds ctermfg=187 ctermbg=234 cterm=NONE
  hi vimOperParen ctermfg=187 ctermbg=234 cterm=NONE
  hi vimPatRegion ctermfg=187 ctermbg=234 cterm=NONE
  hi vimPythonRegion ctermfg=187 ctermbg=234 cterm=NONE
  hi vimRange ctermfg=187 ctermbg=234 cterm=NONE
  hi vimRegion ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSet ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSetEqual ctermfg=187 ctermbg=234 cterm=NONE
  hi vimStdPlugin ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSubst2 ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSubstPat ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSubstRange ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSubstRep ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSubstRep4 ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSynKeyRegion ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSynLine ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSynMatchRegion ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSynMtchCchar ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSynMtchGroup ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSynPatMod ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSynRegion ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSyncLinebreak ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSyncLinecont ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSyncLines ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSyncMatch ctermfg=187 ctermbg=234 cterm=NONE
  hi vimSyncRegion ctermfg=187 ctermbg=234 cterm=NONE
  hi vimUserCmd ctermfg=187 ctermbg=234 cterm=NONE
  hi vimUsrCmd ctermfg=187 ctermbg=234 cterm=NONE
  hi xmlDocType ctermfg=187 ctermbg=234 cterm=NONE
  hi xmlRegion ctermfg=187 ctermbg=234 cterm=NONE
  hi xmlSyncComment ctermfg=187 ctermbg=234 cterm=NONE
  if !s:italics
    hi htmlBoldItalic cterm=bold
    hi htmlBoldUnderlineItalic cterm=bold,underline
    hi htmlItalic cterm=NONE
    hi htmlUnderlineItalic cterm=underline
  endif
  unlet s:t_Co s:italics
  finish
endif

highlight DbgBreakptLine guifg=#ffffff guibg=#7aae29
highlight DbgBreakptSign guifg=#ffffff guibg=#7aae29
highlight DbgCurrentLine guifg=#ffffff guibg=#f5669c
highlight DbgCurrentSign guifg=#ffffff guibg=#f5669c
highlight DbgDisabledSign guifg=#ffffff guibg=#42a7cf
highlight DbgDisabledLine guifg=#ffffff guibg=#42a7cf
highlight DbgCurrentStackPositionSign guifg=#ffffff guibg=#42a7cf
highlight DbgCurrentStackPositionLine guifg=#ffffff guibg=#42a7cf

highlight LspErrorHighlight guibg=#c7c7c7

" Background: dark
" Color: baldFossa #fad07a ~
" Color: baldMacaw #0000ff ~
" Color: boldHeron #80a0ff ~
" Color: boldSquid #BDBDBD ~
" Color: boldZebra #d9d9d9 ~
" Color: busyCamel #ff0000 ~
" Color: busyHyena #00ffff ~
" Color: busyXerus #414141 ~
" Color: calmHeron #302028 ~
" Color: calmLiger #dddddd ~
" Color: calmMouse #E1C0F6 ~
" Color: calmQuail #a0a8b0 ~
" Color: calmStoat #90ee90 ~
" Color: calmXerus #447799 ~
" Color: coolBison #606060 ~
" Color: coolBongo #345fa8 ~
" Color: coolTetra #E87174 ~
" Color: cuteBison #FFDBA5 ~
" Color: cuteFossa #d2ebbe ~
" Color: cuteGoose #ff00ff ~
" Color: cuteHorse #777777 ~
" Color: cuteSloth #b0b8c0 ~
" Color: deadMoose #f0f0f0 ~
" Color: deadOtter #7597c6 ~
" Color: drabBison #648699 ~
" Color: drabSloth #556779 ~
" Color: dullCoati #93B97E ~
" Color: dullMoose #00988E ~
" Color: dumbCamel #7697d6 ~
" Color: dumbRobin #ffffff ~
" Color: dumbSkunk #333333 ~
" Color: easyAkita #405026 ~
" Color: easyGuppy #FEFEFE ~
" Color: easyHeron #101010 ~
" Color: easyXerus #c6b6ee ~
" Color: evilOkapi #b9ed67 ~
" Color: fairAkita #888888 ~
" Color: fairHeron #FBDAFC ~
" Color: fineHuman #540063 ~
" Color: fineSnail #dad085 ~
" Color: freeCamel #de5577 ~
" Color: freeIndri #bebebe ~
" Color: gladBooby #384048 ~
" Color: gladCamel #535d66 ~
" Color: gladGoose #e8e8d3 ~
" Color: gladMolly #8197bf ~
" Color: gladSnake #DEDEDE ~
" Color: glumHorse #00B3A8 ~
" Color: glumSquid #b0d0f0 ~
" Color: goodGecko #9098a0 ~
" Color: goodZorse #FFB981 ~
" Color: hurtHyena #cc8bc9 ~
" Color: hurtLiger #404040 ~
" Color: kindHeron #f0a0c0 ~
" Color: kindLemur #232323 ~
" Color: kindMolly #B8BB26 ~
" Color: kindSkunk #ffb964 ~
" Color: lazyCoral #2d7067 ~
" Color: lazyLemur #8fbfdc ~
" Color: niceCamel #668799 ~
" Color: niceCoral #cf6a4c ~
" Color: openDhole #dd0093 ~
" Color: openPrawn #902020 ~
" Color: openSloth #40000a ~
" Color: paleRobin #ccc5c4 ~
" Color: poorDingo #1f1f1f ~
" Color: poorRobin #c7c7c7 ~
" Color: poorSaola #0000df ~
" Color: realBison #000000 ~
" Color: realCoati #eeeeee ~
" Color: realMolly #7f7f7f ~
" Color: richDingo #bcddbd ~
" Color: richKoala #403c41 ~
" Color: soreDhole #d3d3d3 ~
" Color: soreEagle #FFA0A2 ~
" Color: soreSnail #700009 ~
" Color: sourBongo #437019 ~
" Color: sourIndri #605958 ~
" Color: sourPrawn #c59f6f ~
" Color: sourSnake #ABD9F3 ~
" Color: tameLemur #c6b6fe ~
" Color: tameSquid #465457 ~
" Color: uglyCoati #1c1c1c ~
" Color: uglyDingo #a40073 ~
" Color: vastZorse #65c254 ~
" Color: warmDhole #deebfe ~
" Color: warmFossa #565656 ~
" Color: warmOkapi #556633 ~
" Color: weakGuppy #70b950 ~
" Color: weakRobin #1b1b1b ~
" Color: wildCoati #99ad6a ~
" Color: wildEagle #2b5b77 ~
" Color: zanyBison #1e1e1e ~
" Color: zanyDhole #e12672 ~
" Color: zanySaola #4f0037 ~
" Term colors: busyXerus coolTetra dullCoati goodZorse drabBison calmMouse dullMoose gladSnake boldSquid soreEagle kindMolly cuteBison sourSnake fairHeron glumHorse easyGuppy
" vim: et ts=2 sw=2
