" Name:         parchment_optimized
" Description:  parchment import by tools Colortemplate.
" Maintainer:   Original maintainer https://github.com/ajgrf
" URL:          Original URL https://github.com/ajgrf/parchment
" License:      Vim License (see `:help license`)

" Generated by Colortemplate v2.2.0

" The color scheme is generated but with some corrections

set background=light

hi clear
let g:colors_name = 'parchment_optimized'

let s:t_Co = exists('&t_Co') && !has('gui_running') ? (&t_Co ?? 0) : -1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link CurSearch Search
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link NERDTreeBookmark Normal
hi! link NERDTreeBookmarkName Identifier
hi! link NERDTreeBookmarksHeader Statement
hi! link NERDTreeBookmarksLeader Ignore
hi! link NERDTreeCWD Statement
hi! link NERDTreeClosable Directory
hi! link NERDTreeCurrentNode Search
hi! link NERDTreeDir Directory
hi! link NERDTreeDirSlash Identifier
hi! link NERDTreeExecFile Title
hi! link NERDTreeFile Normal
hi! link NERDTreeFlags Constant
hi! link NERDTreeHelp String
hi! link NERDTreeHelpCommand Identifier
hi! link NERDTreeHelpKey Identifier
hi! link NERDTreeHelpTitle PreProc
hi! link NERDTreeIgnore Ignore
hi! link NERDTreeLinkDir PreProc
hi! link NERDTreeLinkFile PreProc
hi! link NERDTreeLinkTarget Type
hi! link NERDTreeOpenable Directory
hi! link NERDTreePart Special
hi! link NERDTreePartFile Type
hi! link NERDTreeRO WarningMsg
hi! link NERDTreeToggleOff WarningMsg
hi! link NERDTreeToggleOn Question
hi! link NERDTreeUp Directory
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link StorageClass Type
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link bufExplorerActBuf Identifier
hi! link bufExplorerAltBuf String
hi! link bufExplorerBufNbr Constant
hi! link bufExplorerCurBuf Type
hi! link bufExplorerHelp Special
hi! link bufExplorerHidBuf Constant
hi! link bufExplorerInactBuf Comment
hi! link bufExplorerLockedBuf Special
hi! link bufExplorerMapping NonText
hi! link bufExplorerModBuf Statement
hi! link bufExplorerOpenIn Identifier
hi! link bufExplorerSortBy String
hi! link bufExplorerSortType String
hi! link bufExplorerSplit NonText
hi! link bufExplorerTitle NonText
hi! link bufExplorerToggleOpen Identifier
hi! link bufExplorerToggleSplit NonText
hi! link bufExplorerUnlBuf Comment
hi! link colortemplateArrow Delimiter
hi! link colortemplateAttr Statement
hi! link colortemplateAttrs String
hi! link colortemplateCommand PreProc
hi! link colortemplateComment Comment
hi! link colortemplateConstant Type
hi! link colortemplateFunction Identifier
hi! link colortemplateGuisp String
hi! link colortemplateHexColor Constant
hi! link colortemplateHiGroup Identifier
hi! link colortemplateKey Special
hi! link colortemplateKeyword Statement
hi! link colortemplateNumber Constant
hi! link colortemplateSpecial Constant
hi! link colortemplateTermCode String
hi! link colortemplateTodo Todo
hi! link colortemplateVerb Title
hi! link helpBacktick Ignore
hi! link helpBar Ignore
hi! link helpBoolean Constant
hi! link helpCharacter Constant
hi! link helpCommand Comment
hi! link helpComment Comment
hi! link helpConditional Statement
hi! link helpConstant Constant
hi! link helpDebug Special
hi! link helpDefine PreProc
hi! link helpDelimiter Delimiter
hi! link helpDeprecated Todo
hi! link helpError Error
hi! link helpException Statement
hi! link helpFloat Constant
hi! link helpFunction Identifier
hi! link helpHeader PreProc
hi! link helpHeadline Statement
hi! link helpHyperTextEntry String
hi! link helpHyperTextJump Identifier
hi! link helpIdentifier Identifier
hi! link helpIgnore Ignore
hi! link helpInclude PreProc
hi! link helpKeyword Statement
hi! link helpLabel Statement
hi! link helpMacro PreProc
hi! link helpNotVi Special
hi! link helpNote Todo
hi! link helpNumber Constant
hi! link helpOperator Statement
hi! link helpOption Type
hi! link helpPreCondit PreProc
hi! link helpPreProc PreProc
hi! link helpRepeat Statement
hi! link helpSectionDelim PreProc
hi! link helpSpecial Special
hi! link helpSpecialChar Special
hi! link helpSpecialComment SpecialComment
hi! link helpStar Ignore
hi! link helpStatement Statement
hi! link helpStorageClass Type
hi! link helpString String
hi! link helpStructure Type
hi! link helpTag Special
hi! link helpTodo Todo
hi! link helpType Type
hi! link helpTypedef Type
hi! link helpURL String
hi! link helpUnderlined Underlined
hi! link helpVim Identifier
hi! link helpWarning Todo
hi! link pythonAsync Statement
hi! link pythonBuiltin Identifier
hi! link pythonComment Comment
hi! link pythonConditional Statement
hi! link pythonDecorator PreProc
hi! link pythonDecoratorName Identifier
hi! link pythonDoctest Special
hi! link pythonDoctestValue PreProc
hi! link pythonEscape Special
hi! link pythonException Statement
hi! link pythonExceptions Type
hi! link pythonFunction Identifier
hi! link pythonInclude PreProc
hi! link pythonNumber Constant
hi! link pythonOperator Statement
hi! link pythonQuotes String
hi! link pythonRawString String
hi! link pythonRepeat Statement
hi! link pythonStatement Statement
hi! link pythonString String
hi! link pythonTodo Todo
hi! link pythonTripleQuotes String
hi! link vim9Comment Comment
hi! link vim9LineComment Comment
hi! link vimAbb Statement
hi! link vimAddress Constant
hi! link vimAuHighlight Statement
hi! link vimAugroupError Error
hi! link vimAugroupKey Statement
hi! link vimAutoCmd Statement
hi! link vimAutoCmdMod Special
hi! link vimAutoCmdOpt PreProc
hi! link vimAutoEvent Type
hi! link vimAutoSet Statement
hi! link vimBehave Statement
hi! link vimBehaveError Error
hi! link vimBehaveModel Statement
hi! link vimBracket Delimiter
hi! link vimBufnrWarn WarningMsg
hi! link vimCmplxRepeat Special
hi! link vimCollClassErr Error
hi! link vimCommand Statement
hi! link vimComment Comment
hi! link vimCommentString String
hi! link vimCommentTitle PreProc
hi! link vimCondHL Statement
hi! link vimContinue Special
hi! link vimCtrlChar Special
hi! link vimEchoHL Statement
hi! link vimEchoHLNone Type
hi! link vimElseIfErr Error
hi! link vimElseif Statement
hi! link vimEmbedError Error
hi! link vimEnvvar PreProc
hi! link vimErrSetting Error
hi! link vimError Error
hi! link vimEscape Special
hi! link vimFBVar Identifier
hi! link vimFTCmd Statement
hi! link vimFTError Error
hi! link vimFTOption Type
hi! link vimFgBgAttrib PreProc
hi! link vimFold Folded
hi! link vimFunc Error
hi! link vimFuncEcho Statement
hi! link vimFuncKey Statement
hi! link vimFuncName Identifier
hi! link vimFuncVar Identifier
hi! link vimFunctionError Error
hi! link vimGroup Type
hi! link vimGroupAdd Special
hi! link vimGroupName Type
hi! link vimGroupRem Special
hi! link vimGroupSpecial Special
hi! link vimHLGroup Type
hi! link vimHLMod PreProc
hi! link vimHiAttrib PreProc
hi! link vimHiAttribList Error
hi! link vimHiCTerm Type
hi! link vimHiClear Statement
hi! link vimHiCtermError Error
hi! link vimHiCtermFgBg Type
hi! link vimHiCtermul Type
hi! link vimHiGroup Type
hi! link vimHiGui Type
hi! link vimHiGuiFgBg Type
hi! link vimHiGuiFont Type
hi! link vimHiGuiRgb Constant
hi! link vimHiKeyError Error
hi! link vimHiNmbr Constant
hi! link vimHiStartStop Type
hi! link vimHiTerm Type
hi! link vimHighlight Statement
hi! link vimInsert String
hi! link vimIskSep Delimiter
hi! link vimKeyCode Identifier
hi! link vimKeyCodeError Error
hi! link vimKeyword Statement
hi! link vimLet Statement
hi! link vimLetHereDoc String
hi! link vimLetHereDocStart Special
hi! link vimLetHereDocStop Special
hi! link vimLineComment Comment
hi! link vimMap Statement
hi! link vimMapBang Statement
hi! link vimMapMod Delimiter
hi! link vimMapModErr Error
hi! link vimMapModKey vimFuncSID
hi! link vimMark Constant
hi! link vimMarkNumber Constant
hi! link vimMenuMod Delimiter
hi! link vimMenuName PreProc
hi! link vimMenuNameMore PreProc
hi! link vimMtchComment Comment
hi! link vimNorm Statement
hi! link vimNotFunc Statement
hi! link vimNotPatSep String
hi! link vimNotation Special
hi! link vimNumber Constant
hi! link vimOper Statement
hi! link vimOperError Error
hi! link vimOption PreProc
hi! link vimParenSep Delimiter
hi! link vimPatSep Special
hi! link vimPatSepErr Error
hi! link vimPatSepR Special
hi! link vimPatSepZ Special
hi! link vimPatSepZone String
hi! link vimPattern Type
hi! link vimPlainMark Constant
hi! link vimPlainRegister Special
hi! link vimRegister Special
hi! link vimScriptDelim Comment
hi! link vimSearch String
hi! link vimSearchDelim Statement
hi! link vimSep Delimiter
hi! link vimSetMod PreProc
hi! link vimSetSep Statement
hi! link vimSetString String
hi! link vimSpecFile Identifier
hi! link vimSpecFileMod Identifier
hi! link vimSpecial Type
hi! link vimStatement Statement
hi! link vimString String
hi! link vimStringCont String
hi! link vimStringEnd String
hi! link vimSubst Statement
hi! link vimSubst1 Statement
hi! link vimSubstDelim Delimiter
hi! link vimSubstFlagErr Error
hi! link vimSubstFlags Special
hi! link vimSubstSubstr Special
hi! link vimSubstTwoBS String
hi! link vimSynCase Type
hi! link vimSynCaseError Error
hi! link vimSynContains Special
hi! link vimSynError Error
hi! link vimSynKeyContainedin Special
hi! link vimSynKeyOpt Special
hi! link vimSynMtchGrp Special
hi! link vimSynMtchOpt Special
hi! link vimSynNextgroup Special
hi! link vimSynNotPatRange String
hi! link vimSynOption Special
hi! link vimSynPatRange String
hi! link vimSynReg Type
hi! link vimSynRegOpt Special
hi! link vimSynRegPat String
hi! link vimSynType Type
hi! link vimSyncC Type
hi! link vimSyncError Error
hi! link vimSyncGroup Type
hi! link vimSyncGroupName Type
hi! link vimSyncKey Type
hi! link vimSyncNone Type
hi! link vimSyntax Statement
hi! link vimTodo Todo
hi! link vimType Type
hi! link vimUnmap Statement
hi! link vimUserAttrb Type
hi! link vimUserAttrbCmplt Type
hi! link vimUserAttrbCmpltFunc Special
hi! link vimUserAttrbError Error
hi! link vimUserAttrbKey PreProc
hi! link vimUserCmdError Error
hi! link vimUserCommand Statement
hi! link vimUserFunc Normal
hi! link vimVar Identifier
hi! link vimWarn WarningMsg
hi! link vimoperStar Statement

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#880000', '#005500', '#663311', '#004488', '#770077', '#007777', '#eeeecc', '#000000', '#880000', '#005500', '#663311', '#004488', '#770077', '#007777', '#ffffea']
endif
hi Normal guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi ColorColumn guifg=#000000 guibg=#ffeaea gui=NONE cterm=NONE
hi ColortemplateInfoBg guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi ColortemplateInfoBlack guifg=#000000 guibg=#000000 gui=NONE cterm=NONE
hi ColortemplateInfoFg guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi ColortemplateInfoSp guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi Comment guifg=#663311 guibg=#ffffea gui=italic cterm=italic
hi Conceal guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
" Original Constant didn`t highlight
" hi Constant guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi Constant guifg=#770077 guibg=#ffffea gui=NONE cterm=NONE
hi Cursor guifg=#000000 guibg=#ffffea gui=reverse cterm=reverse
hi CursorColumn guifg=#000000 guibg=#eeeecc gui=NONE cterm=NONE
hi CursorLine guifg=#000000 guibg=#eeeecc gui=NONE cterm=NONE
hi CursorLineNr guifg=#000000 guibg=#eeee9e gui=NONE cterm=NONE
hi Delimiter guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi DiffAdd guifg=#005500 guibg=#eaffea gui=NONE cterm=NONE
hi DiffChange guifg=#770077 guibg=#ffeaff gui=NONE cterm=NONE
hi DiffDelete guifg=#880000 guibg=#ffeaea gui=NONE cterm=NONE
hi DiffText guifg=#770077 guibg=#ffeaff gui=bold cterm=bold
hi Directory guifg=#004488 guibg=#ffffea gui=bold cterm=bold
hi EndOfBuffer guifg=#007777 guibg=#ffffea gui=NONE cterm=NONE
hi Error guifg=#ffffea guibg=#880000 gui=NONE cterm=NONE
hi ErrorMsg guifg=#ffffea guibg=#880000 gui=bold cterm=bold
hi FoldColumn guifg=#000000 guibg=#eaeaea gui=NONE cterm=NONE
hi Folded guifg=#000000 guibg=#eaeaea gui=NONE cterm=NONE
hi Identifier guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi Ignore guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi IncSearch guifg=#000000 guibg=#cceeff gui=bold cterm=bold
hi LedgerNegativeNumber guifg=#880000 guibg=#ffffea gui=NONE cterm=NONE
hi LedgerPending guifg=#000000 guibg=#ffffea gui=bold cterm=bold
hi LineNr guifg=#000000 guibg=#eaeaea gui=NONE cterm=NONE
hi LineNrAbove guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi LineNrBelow guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi MatchParen guifg=#000000 guibg=#cceeff gui=NONE cterm=NONE
hi ModeMsg guifg=#000000 guibg=#ffffea gui=bold cterm=bold
hi MoreMsg guifg=#000000 guibg=#ffffea gui=bold cterm=bold
hi NERDTreeLink guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi NERDTreeNodeDelimiters guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi NonText guifg=#007777 guibg=#eaffff gui=NONE cterm=NONE
hi Pmenu guifg=#000000 guibg=#eaffff gui=NONE cterm=NONE
hi PmenuSbar guifg=#000000 guibg=#eaffff gui=NONE cterm=NONE
hi PmenuSel guifg=#ffffea guibg=#007777 gui=bold cterm=bold
hi PmenuThumb guifg=#000000 guibg=#007777 gui=NONE cterm=NONE
hi PreProc guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi Question guifg=#000000 guibg=#ffffea gui=bold cterm=bold
hi QuickFixLine guifg=#000000 guibg=#cceeff gui=NONE cterm=NONE
hi Search guifg=#000000 guibg=#cceeff gui=underline cterm=underline
hi SignColumn guifg=#000000 guibg=#eaeaea gui=NONE cterm=NONE
hi Special guifg=#770077 guibg=#ffffea gui=NONE cterm=NONE
hi SpecialComment guifg=#663311 guibg=#ffffea gui=NONE cterm=NONE
hi SpecialKey guifg=#007777 guibg=#eaffff gui=NONE cterm=NONE
hi SpellBad guifg=#880000 guibg=#ffffea guisp=#ff0000 gui=undercurl cterm=undercurl
hi SpellCap guifg=#005500 guibg=#ffffea guisp=#0000ff gui=undercurl cterm=undercurl
hi SpellLocal guifg=#005500 guibg=#ffffea guisp=#008b8b gui=undercurl cterm=undercurl
hi SpellRare guifg=#005500 guibg=#ffffea guisp=#ff00ff gui=undercurl cterm=undercurl
" Original Statement didn`t highlight
" hi Statement guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi Statement guifg=#004488 guibg=#ffffea gui=NONE cterm=NONE
hi StatusLine guifg=#000000 guibg=#eaeaea gui=bold cterm=bold
hi StatusLineNC guifg=#808075 guibg=#eaeaea gui=NONE cterm=NONE
hi StatusLineTerm guifg=#ffffea guibg=#006400 gui=bold cterm=bold
hi StatusLineTermNC guifg=#ffffea guibg=#006400 gui=NONE cterm=NONE
hi String guifg=#005500 guibg=#ffffea gui=NONE cterm=NONE
hi TabLine guifg=#000000 guibg=#eaeaea gui=NONE cterm=NONE
hi TabLineFill guifg=#000000 guibg=#eaeaea gui=NONE cterm=NONE
hi TabLineSel guifg=#000000 guibg=#eaeaea gui=bold cterm=bold
hi Title guifg=#770077 guibg=#ffffea gui=NONE cterm=NONE
hi Todo guifg=#004488 guibg=#ffffea gui=bold cterm=bold
hi ToolbarButton guifg=#ffffff guibg=#666666 gui=bold cterm=bold
hi ToolbarLine guifg=#000000 guibg=#d3d3d3 gui=NONE cterm=NONE
hi Type guifg=#004488 guibg=#ffffea gui=NONE cterm=NONE
hi Underlined guifg=#000000 guibg=#ffffea gui=underline cterm=underline
hi VertSplit guifg=#000000 guibg=#eaeaea gui=NONE cterm=NONE
hi Visual guifg=#000000 guibg=#eeee9e gui=NONE cterm=NONE
hi VisualNOS guifg=#000000 guibg=#ffffea gui=bold,underline cterm=bold,underline
hi WarningMsg guifg=#880000 guibg=#ffffea gui=NONE cterm=NONE
hi WildMenu guifg=#ffffea guibg=#007777 gui=bold cterm=bold
hi colortemplateAux guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi colortemplateColorDef guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi colortemplateColorSpec guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi colortemplateCompound guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi colortemplateHelp guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi colortemplateReset guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi colortemplateVim guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi diffAdded guifg=#005500 guibg=#eaffea gui=NONE cterm=NONE
hi diffFile guifg=#770077 guibg=#ffffea gui=NONE cterm=NONE
hi diffIndexLine guifg=#770077 guibg=#ffffea gui=NONE cterm=NONE
hi diffLine guifg=#770077 guibg=#ffeaff gui=NONE cterm=NONE
hi diffRemoved guifg=#880000 guibg=#ffeaea gui=NONE cterm=NONE
hi diffSubname guifg=#770077 guibg=#ffeaff gui=NONE cterm=NONE
hi fzf1 guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi fzf2 guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi fzf3 guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi gitcommitBranch guifg=#000000 guibg=#ffffea gui=italic cterm=italic
hi gitcommitHeader guifg=#663311 guibg=#ffffea gui=italic cterm=italic
hi gitcommitSelectedType guifg=#663311 guibg=#ffffea gui=italic cterm=italic
hi gitcommitType guifg=#663311 guibg=#ffffea gui=italic cterm=italic
hi helpExample guifg=#004488 guibg=#ffffea gui=NONE cterm=NONE
hi helpGraphic guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi helpLeadBlank guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi helpNormal guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi htmlH1 guifg=#000000 guibg=#eaeaea gui=bold cterm=bold
hi htmlH2 guifg=#004488 guibg=#eaffff gui=bold cterm=bold
hi htmlH3 guifg=#005500 guibg=#eaffea gui=bold cterm=bold
hi htmlH4 guifg=#663311 guibg=#ffffea gui=bold cterm=bold
hi htmlH5 guifg=#770077 guibg=#ffffea gui=bold cterm=bold
hi htmlH6 guifg=#007777 guibg=#ffffea gui=bold,italic cterm=bold,italic
hi hyperlink guifg=#007777 guibg=#ffffea gui=underline cterm=underline
hi lCursor guifg=#ffffea guibg=#770077 gui=NONE cterm=NONE
hi mailEmail guifg=#007777 guibg=#ffffea gui=NONE cterm=NONE
hi mailHeader guifg=#004488 guibg=#ffffea gui=NONE cterm=NONE
hi mailHeaderEmail guifg=#007777 guibg=#ffffea gui=NONE cterm=NONE
hi mailHeaderKey guifg=#770077 guibg=#ffffea gui=NONE cterm=NONE
hi mailQuoted1 guifg=#004488 guibg=#ffffea gui=italic cterm=italic
hi mailQuoted2 guifg=#005500 guibg=#ffffea gui=italic cterm=italic
hi mailQuoted3 guifg=#663311 guibg=#ffffea gui=italic cterm=italic
hi mailQuoted4 guifg=#004488 guibg=#ffffea gui=italic cterm=italic
hi mailQuoted5 guifg=#005500 guibg=#ffffea gui=italic cterm=italic
hi mailQuoted6 guifg=#663311 guibg=#ffffea gui=italic cterm=italic
hi mailSignature guifg=#000000 guibg=#ffffea gui=italic cterm=italic
hi mailSubject guifg=#000000 guibg=#eaeaea gui=bold cterm=bold
hi mailURL guifg=#007777 guibg=#ffffea gui=underline cterm=underline
hi markdownBlockQuote guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi markdownBold guifg=#000000 guibg=#ffffea gui=bold cterm=bold
hi markdownBoldItalic guifg=#000000 guibg=#ffffea gui=bold,italic cterm=bold,italic
hi markdownCode guifg=#004488 guibg=#ffffea gui=NONE cterm=NONE
hi markdownCodeBlock guifg=#004488 guibg=#ffffea gui=NONE cterm=NONE
hi markdownH1 guifg=#000000 guibg=#eaeaea gui=bold cterm=bold
hi markdownH2 guifg=#004488 guibg=#eaffff gui=bold cterm=bold
hi markdownH2Delimiter guifg=#004488 guibg=#eaffff gui=bold cterm=bold
hi markdownH3 guifg=#005500 guibg=#eaffea gui=bold cterm=bold
hi markdownH3Delimiter guifg=#005500 guibg=#eaffea gui=bold cterm=bold
hi markdownH4 guifg=#663311 guibg=#ffffea gui=bold cterm=bold
hi markdownH4Delimiter guifg=#663311 guibg=#ffffea gui=bold cterm=bold
hi markdownH5 guifg=#770077 guibg=#ffffea gui=bold cterm=bold
hi markdownH5Delimiter guifg=#770077 guibg=#ffffea gui=bold cterm=bold
hi markdownH6 guifg=#007777 guibg=#ffffea gui=bold,italic cterm=bold,italic
hi markdownH6Delimiter guifg=#007777 guibg=#ffffea gui=bold,italic cterm=bold,italic
hi markdownHeadingDelimiter guifg=#000000 guibg=#eaeaea gui=bold cterm=bold
hi markdownHeadingRule guifg=#000000 guibg=#ffffea gui=bold cterm=bold
hi markdownItalic guifg=#000000 guibg=#ffffea gui=italic cterm=italic
hi markdownLineBreak guifg=#007777 guibg=#ffffea gui=underline cterm=underline
hi markdownUrl guifg=#007777 guibg=#ffffea gui=underline cterm=underline
hi markdownUrlTitleDelimiter guifg=#005500 guibg=#ffffea gui=NONE cterm=NONE
hi nroffEscape guifg=#770077 guibg=#ffffea gui=NONE cterm=NONE
hi nroffSpecial guifg=#770077 guibg=#ffffea gui=NONE cterm=NONE
hi org_block_delimiter guifg=#007777 guibg=#eaffff gui=NONE cterm=NONE
hi org_bold guifg=#000000 guibg=#ffffea gui=bold cterm=bold
hi org_code guifg=#004488 guibg=#ffffea gui=NONE cterm=NONE
hi org_deadline_scheduled guifg=#007777 guibg=#eaffff gui=bold cterm=bold
hi org_heading1 guifg=#000000 guibg=#eaeaea gui=bold cterm=bold
hi org_heading2 guifg=#004488 guibg=#eaffff gui=bold cterm=bold
hi org_heading3 guifg=#005500 guibg=#eaffea gui=bold cterm=bold
hi org_heading4 guifg=#663311 guibg=#ffffea gui=bold cterm=bold
hi org_heading5 guifg=#770077 guibg=#ffffea gui=bold cterm=bold
hi org_heading6 guifg=#007777 guibg=#ffffea gui=bold,italic cterm=bold,italic
hi org_heading7 guifg=#005500 guibg=#ffffea gui=bold,italic cterm=bold,italic
hi org_italic guifg=#000000 guibg=#ffffea gui=italic cterm=italic
hi org_key_identifier guifg=#007777 guibg=#eaffff gui=NONE cterm=NONE
hi org_properties_delimiter guifg=#007777 guibg=#eaffff gui=bold cterm=bold
hi org_shade_stars guifg=#eeeecc guibg=#ffffea gui=NONE cterm=NONE
hi org_subtask_number guifg=#880000 guibg=#ffeaea gui=NONE cterm=NONE
hi org_subtask_number_all guifg=#004488 guibg=#cceeff gui=NONE cterm=NONE
hi org_subtask_percent guifg=#880000 guibg=#ffeaea gui=NONE cterm=NONE
hi org_subtask_percent_100 guifg=#004488 guibg=#cceeff gui=NONE cterm=NONE
hi org_table guifg=#005500 guibg=#eaffea gui=NONE cterm=NONE
hi org_table_separator guifg=#005500 guibg=#eaffea gui=NONE cterm=NONE
hi org_timestamp guifg=#004488 guibg=#ffffea gui=NONE cterm=NONE
hi org_title guifg=#000000 guibg=#ffffea gui=bold cterm=bold
hi org_todo_keyword_DONE guifg=#004488 guibg=#cceeff gui=bold cterm=bold
hi org_todo_keyword_TODO guifg=#880000 guibg=#ffeaea gui=bold cterm=bold
hi org_underline guifg=#000000 guibg=#ffffea gui=underline cterm=underline
hi org_verbatim guifg=#004488 guibg=#ffffea gui=NONE cterm=NONE
hi pythonAttribute guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi pythonMatrixMultiply guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi pythonSpaceError guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi pythonSync guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi rstEmphasis guifg=#000000 guibg=#ffffea gui=italic cterm=italic
hi rstHyperlinkReference guifg=#007777 guibg=#ffffea gui=underline cterm=underline
hi rstInlineLiteral guifg=#004488 guibg=#ffffea gui=NONE cterm=NONE
hi rstInterpretedTextOrHyperlinkReference guifg=#007777 guibg=#ffffea gui=underline cterm=underline
hi rstSections guifg=#000000 guibg=#ffffea gui=bold cterm=bold
hi rstSimpleTable guifg=#005500 guibg=#eaffea gui=NONE cterm=NONE
hi rstStandaloneHyperlink guifg=#007777 guibg=#ffffea gui=underline cterm=underline
hi rstStrongEmphasis guifg=#000000 guibg=#ffffea gui=bold cterm=bold
hi rstTable guifg=#005500 guibg=#eaffea gui=NONE cterm=NONE
hi rstTableLines guifg=#005500 guibg=#eaffea gui=NONE cterm=NONE
hi shCommandSub guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi shDeref guifg=#770077 guibg=#ffffea gui=NONE cterm=NONE
hi shEcho guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi shQuote guifg=#005500 guibg=#ffffea gui=NONE cterm=NONE
hi tmuxFormatString guifg=#770077 guibg=#ffffea gui=NONE cterm=NONE
hi tmuxKey guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi today guifg=#004488 guibg=#ffffea gui=bold cterm=bold
hi vimAuSyntax guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimAugroup guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimAugroupSyncA guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimAutoCmdSfxList guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimAutoCmdSpace guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimAutoEventList guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimClusterName guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimCmdSep guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimCollClass guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimCollection guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimComFilter guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimCommentTitleLeader guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimEcho guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimEscapeBrace guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimExecute guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimExtCmd guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimFiletype guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimFilter guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimFuncBlank guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimFuncBody guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimFuncSID guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimFunction guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimGlobal guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimGroupList guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimHiBang guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimHiCtermColor guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimHiFontname guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimHiGuiFontname guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimHiKeyList guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimHiLink guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimHiTermcap guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimIsCommand guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimIskList guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimMapLhs guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimMapRhs guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimMapRhsExtend guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimMenuBang guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimMenuMap guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimMenuPriority guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimMenuRhs guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimNormCmds guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimOperParen guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimPatRegion guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimPythonRegion guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimRange guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimRegion guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSet guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSetEqual guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimStdPlugin guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSubst2 guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSubstPat guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSubstRange guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSubstRep guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSubstRep4 guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSynKeyRegion guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSynLine guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSynMatchRegion guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSynMtchCchar guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSynMtchGroup guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSynPatMod guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSynRegion guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSyncLinebreak guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSyncLinecont guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSyncLines guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSyncMatch guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimSyncRegion guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimUserCmd guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi vimUsrCmd guifg=#000000 guibg=#ffffea gui=NONE cterm=NONE
hi week_agenda guifg=#004488 guibg=#ffffea gui=bold cterm=bold
if !s:italics
  hi Comment gui=NONE cterm=NONE
  hi gitcommitBranch gui=NONE cterm=NONE
  hi gitcommitHeader gui=NONE cterm=NONE
  hi gitcommitSelectedType gui=NONE cterm=NONE
  hi gitcommitType gui=NONE cterm=NONE
  hi htmlH6 gui=bold cterm=bold
  hi mailQuoted1 gui=NONE cterm=NONE
  hi mailQuoted2 gui=NONE cterm=NONE
  hi mailQuoted3 gui=NONE cterm=NONE
  hi mailQuoted4 gui=NONE cterm=NONE
  hi mailQuoted5 gui=NONE cterm=NONE
  hi mailQuoted6 gui=NONE cterm=NONE
  hi mailSignature gui=NONE cterm=NONE
  hi markdownBoldItalic gui=bold cterm=bold
  hi markdownH6 gui=bold cterm=bold
  hi markdownH6Delimiter gui=bold cterm=bold
  hi markdownItalic gui=NONE cterm=NONE
  hi org_heading6 gui=bold cterm=bold
  hi org_heading7 gui=bold cterm=bold
  hi org_italic gui=NONE cterm=NONE
  hi rstEmphasis gui=NONE cterm=NONE
endif

hi ExtraWhitespace guifg=#e8e8d3 guibg=#888888 gui=NONE cterm=NONE


" Background: light
" Color: baldSkunk #eaeaea ~
" Color: boldBooby #008b8b ~
" Color: coolGuppy #ff0000 ~
" Color: deadAkita #808075 ~
" Color: deadMacaw #eeee9e ~
" Color: drabCamel #663311 ~
" Color: dumbKoala #d3d3d3 ~
" Color: easyGoose #ffeaea ~
" Color: fairMacaw #eeeecc ~
" Color: fineLlama #ffeaff ~
" Color: freeSaola #004488 ~
" Color: goodCrane #888888 ~
" Color: goodHuman #666666 ~
" Color: openEagle #005500 ~
" Color: openLlama #770077 ~
" Color: poorOtter #880000 ~
" Color: poorQuail #000000 ~
" Color: richPrawn #ffffea ~
" Color: soreMouse #007777 ~
" Color: sourSheep #e8e8d3 ~
" Color: sourSquid #0000ff ~
" Color: warmBison #ff00ff ~
" Color: weakBongo #ffffff ~
" Color: wildHuman #eaffea ~
" Color: wildTiger #006400 ~
" Color: zanyHuman #cceeff ~
" Color: zanyLiger #eaffff ~
" Term colors: poorQuail poorOtter openEagle drabCamel freeSaola openLlama soreMouse fairMacaw poorQuail poorOtter openEagle drabCamel freeSaola openLlama soreMouse richPrawn
" vim: et ts=2 sw=2
